### PR TITLE
Refactor prepareBasket to mapreduce instead of foreach.

### LINKED ISSUE #17: Rewrite potential reduce
https://github.com/dotkom/mysterious-powerking-conspiracy/blob/master/src/api/ow4.ts#L12

This can be written like this:

```javascript
b=a.reduce((count, curr) => {
  if (count[curr.id] !== undefined) {
    count[curr.id]++;
  } else {
    count[curr.id] = 1;
  }

  return count;
}, {});
```

### PR DESCRIPTION
**Pull request by sklirg**
Fixes #17

### CODE REVIEW

**Comment by sklirg** [comment]
I'm not 100% satisfied with it, but at least it's immutable. 🙈 

Might have another stab at this for the fun of it.

**Comment by FredrikAugust** [comment]
Wouldn't this work?

```typescript
return basket.reduce((count: {[id: string]: number}, curr: IBasketItem) => {
  if (count[curr.id] !== undefined) {
    count[curr.id]++;
  } else {
    count[curr.id] = 1;
  }

  return count;
}, {} as {[id: string]: number});
```

It's not immutable though, but it's pretty concise and easy to read.

If you must have immutability, something like this should also work (_I think_):

```typescript
return basket.reduce((count: {[id: string]: number}, curr: IBasketItem) => ({
  ...count, [curr.id]: (count[curr.id] + 1 || 1)
}), {} as {[id: string]: number});
```

I can try it out later, but if you have an opportunity, that'd be great!

**Comment by FredrikAugust** [comment]
And then you'd of course need the mapping to the appropriate format.

**Comment by FredrikAugust** [comment]
I guess we could also shave off some bytes be cutting down the var names:

```typescript
return b.reduce((c: {[id: string]: number}, e: IBasketItem) => ({
  ...c, [e.id]: (c[e.id] + 1 || 1)
}), {} as {[id: string]: number});
```

And do we really need types here, implicit any for the win

```typescript
return b.reduce((c, e) => ({
  ...c, [e.id]: (c[e.id] + 1 || 1)
}), {});
```

Semicolons are optional

```typescript
return b.reduce((c, e) => ({
  ...c, [e.id]: (c[e.id] + 1 || 1)
}), {})
```

And we can wrap it in a returning anon fat-arrow function

```typescript
b.reduce((c, e) => ({
  ...c, [e.id]: (c[e.id] + 1 || 1)
}), {})
```

JavaScript coercion is fun! (if it's not defined, we'll get undefined. `!!undefined` is false, which is the same as `0` in JS math, so `!!undefined + 1 == 1`!)

```typescript
b.reduce((c, e) => ({
  ...c, [e.id]: !!c[e.id] + 1
}), {})
```

Whitespace? Bah! Preposterous!

```typescript
b.reduce((c,e)=>({...c,[e.id]:!!c[e.id]+1}),{})
```

There we go. One line.

**Comment by sklirg** [comment]
Hah, awesome.

I'd go for readability over bytes since we'll probably minify the code for
production anyways.

I might whip up a test case for this and see what works or not. I mostly
did it as a fun exercise.

**Comment by FredrikAugust** [comment]
Of course :) Just got bored while looking at this and tried to golf it.

**Pull request closed without merging**
