### PR TITLE
Auth app, user, purchase request and RFID support

### PR DESCRIPTION
**Pull request by FredrikAugust**
Implemented:

* auth app with ow4
* login with rfid (using your student card)
* purchase stuff

:trumpet: :crab: :trumpet: :crab: :trumpet: :crab: :trumpet: :crab:

### CODE REVIEW

**Comment by FredrikAugust** [comment]
@Aborysa Could you look this over, and perhaps try it at the office with the RFID scanner?

**Comment by FredrikAugust** [comment]
By the way, you have to run it with `NODE_ENV=production yarn start` to get the features implemented here, as they are mocked by default`.

**Comment by sardred** [comment]
> By the way, you have to run it with `NODE_ENV=production yarn start` to get the features implemented here

Add this to the README.md maybe

**Comment by FredrikAugust** [comment]
I considered it, but I'll implement two yarn start commands for dev and
prod respectively instead, perhaps even as a Makefile.

Thanks for your suggestion though :)

**Pull request merged**
